sonar.projectKey=luizsimione_physics-art-engine
sonar.organization=luizsimione

sonar.sources=backend/src,simulation-engine/src,simulation-engine/include
sonar.tests=backend/src
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.spec.ts

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

sonar.typescript.tsconfigPath=backend/tsconfig.json

sonar.sourceEncoding=UTF-8
